### PR TITLE
[SIMD.js] Fix no defination of SIMD.Int32x4.load2

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-6272

### CODE REVIEW

**Comment by rakuco** [comment]
looks sane to me. what do you think, @huningxin?
remember you'll also need to cherry-pick this to Crosswalk 18 -- let me know if you'll be away for the Chinese new year so I can do that myself if necessary.

**Comment by rakuco** [comment]
Sorry about that, but you'll need to rebase this change, we're moving to a newer M48 and master has been rebased.

**Comment by rakuco** [comment]
I've also created a separate ticket (XWALK-6279) to track cherry-picking this to Crosswalk 18.

**Comment by chuan9** [comment]
@rakuco Sorry for late response. Should I cherry-pick this commit and https://github.com/crosswalk-project/v8-crosswalk/pull/129#issuecomment-180344580 to crosswalk-18/48.0.2564.109 today?

**Comment by rakuco** [comment]
We need to merge this change into master first (I'm waiting for @huningxin to take a look at the patch before merging), but after that it needs to be backported, yes.
As for #129, it can be backported right away.

**Comment by huningxin** [comment]
Sorry for late response. The code LGTM.

**Comment by rakuco** [comment]
Merging, thanks for the review.
@chuan9: remember to roll `DEPS.xwalk` in Crosswalk master, backport this fix to v8-crosswalk's branch corresponding to Crosswalk 17 and then roll `DEPS.xwalk` in Crosswalk's crosswalk-17 branch.

**Comment by rakuco** [comment]
Sorry, I meant Crosswalk 18.

**Comment by chuan9** [comment]
@rakuco got it. Thanks for tips!

**Pull request merged**
