### PR TITLE
M44: Enable SIMD.js in v8-crosswalk

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-4207

### CODE REVIEW

**Comment by rakuco** [comment]
thanks!
ping @huningxin

**Comment by huningxin** [comment]
@chuan9 , Thanks! I will take look at this today.

**Comment by huningxin** [comment]
Code LGTM. One nit in commit log, please merge the conflicts in https://github.com/chuan9/v8-crosswalk/commit/019780837766c63669e60f6f7949acc5379b9035.

Once merged, please roll v8 and enable SIMD in Crosswalk. Like https://github.com/crosswalk-project/crosswalk/commit/bfdc77525257db4e6ce04b14bbed396e16bbd9d5 and https://github.com/crosswalk-project/crosswalk/commit/36593f7d06aed2edf682fc3c15c7e8abbcbb4c10.

Thanks!

**Comment by chuan9** [comment]
@huningxin ok,I will do that after merged, thanks!

**Comment by rakuco** [comment]
so are we ready to land now?

**Comment by huningxin** [comment]
@chuan9 , commit log LGTM. @rakuco , we are ready. Thanks!

**Comment by rakuco** [comment]
thanks, please remember to roll `DEPS.xwalk`.

**Comment by chuan9** [comment]
@rakuco Done, thanks~

**Pull request merged**
