### PR TITLE
M45: Rebase SIMD.js patches

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-4752, BUG=XWALK-4909, BUG=XWALK-4910. 
Test result summary
IA32  OK
ARM OK
X64  OK

Details:
Command: make ia32.release.check.
make[1]: Leaving directory `/home/lc/workspace/v8_crosswalk/v8-crosswalk-rebase/v8/out'
>>> running presubmit tests
Running C++ lint check...
No changes in files detected. Skipping cpplint check.
Running copyright header, trailing whitespaces and two empty lines between declarations check...
Total violating files: 0
Runtime/Natives name clashes: checked 706/1181 functions, all good.
>>> Running tests for ia32.release
No connection to distribution server; running tests locally. [02:19|% 100|+ 22728|-   0]: Done

Command: make arm.release.check
make[1]: Leaving directory `/home/lc/workspace/v8_crosswalk/v8-crosswalk-rebase/v8/out'
>>> running presubmit tests
Running C++ lint check...
No changes in files detected. Skipping cpplint check.
Running copyright header, trailing whitespaces and two empty lines between declarations check...
Total violating files: 0
Runtime/Natives name clashes: checked 706/1181 functions, all good.
>>> Running tests for arm.release
No connection to distribution server; running tests locally.[12:29|% 100|+ 22874|-   0]: Done 

Command: make x64.release.check
make[1]: Leaving directory `/home/lc/workspace/v8_crosswalk/v8-crosswalk-rebase/v8/out'
>>> running presubmit tests
Running C++ lint check...
No changes in files detected. Skipping cpplint check.
Running copyright header, trailing whitespaces and two empty lines between declarations check...
Total violating files: 0
Runtime/Natives name clashes: checked 706/1181 functions, all good.
>>> Running tests for x64.release
No connection to distribution server; running tests locally.[02:28|% 100|+ 22967|-   0]: Done     

Performance Test:
Command:out/ia32.release/d8 --simd-object --allow-natives-syntax mandlebrot.js
Result:
Mandelbrot:            Iterations(    723356), SIMD(  270ms), Non-SIMD(  999ms), Speedup(3.700)

### CODE REVIEW

**Comment by rakuco** [comment]
ping @huningxin

**Comment by huningxin** [comment]
Thanks for the rebasing, @chuan9 !

Some comments from me:

1. Please file a bug and state the reason that why we need to revert the upstream Float32x4 patches. My understanding is the major reason is upstream Float32x4 is not optimized by Crankshaft which is slow.
2. In this version, you removed the SIMD Typed Array which aligns to latest SIMD.js spec. It is good. However, the commit log still has them. So 1) please file a bug about SIMD Typed Array removal; 2) update the commit log according to this.
3. In the Crankshaft patch, the commit log has two sections of conflicts which is confusing. So please only keep the conflicts section for this rebase.
4. As `next` branch doesn't have buildbots, please post the testing results of ia32, x64 and arm here for reference. If you have performance numbers here, it would be better.
5. I noticed you filed a bug which mentions deoptimization has issue. Is it related to this PR? If yes, please paste the link here. It would be good for people reviewing this PR.

**Comment by chuan9** [comment]
Thanks,@huningxin. I just do the following things.
1. File a bug XWALK-4910 and state the reason why I revert the upstream Float32x4 patches. The reasons are  stated in XWALK-4910
2. File a bug XWALK-4909 about SIMD Typed Array removal; update the commit log.
3. Revise the conflicts in the commit log.
4. I upload the testing results of ia32, x64, and arm arches and give the performance test result of mandlebrot.js, the only performance test case which not use SIMD Typed Array.
5. I revise the bug XWALK-4905 which describes deoptimization issue, paste the link in bug description.

**Comment by huningxin** [comment]
Thanks, @chuan9 ! The result is great.

LGTM.

**Comment by rakuco** [comment]
Is XWALK-4910 related to the two commits reverting previous patches in this PR? I noticed that the original commits are from upstream, which means it can be troublesome to revert them in future rebases since V8 changes a lot between each release. Is there a plan to fix those commits upstream, or are there fixes in upstream's master branch?

**Comment by huningxin** [comment]
> Is XWALK-4910 related to the two commits reverting previous patches in this PR?

Yes.

> I noticed that the original commits are from upstream, which means it can be troublesome to revert them in future rebases since V8 changes a lot between each release. 

Yes. The two commits are from upstream. We revert them because they (the SIMD.js API) are development in progress. In this version of V8, the SIMD.js implemented by upstream only has Float32x4. The implementation is not completed and not optimized (leads to low performance).

> Is there a plan to fix those commits upstream, or are there fixes in upstream's master branch?

It is not a fix. The plan is to we would make our implementation work with upstream implementation gradually. I think in next rebase, given Float32x4, Int32x4 and Float64x2 etc., are ready in runtime implementation in upstream master. We would only keep our Crankshaft optimization (with some adjustment).

@rakuco , does it make sense to you?

**Comment by rakuco** [comment]
ok, let's see how this goes :-)

**Comment by rakuco** [comment]
I'll take care of rolling v8-crosswalk in crosswalk's next branch

**Pull request merged**
