### PR TITLE
SIMD.js rebase to M43

### PR DESCRIPTION
**Pull request by huningxin**

### CODE REVIEW

**Comment by huningxin** [comment]
@chuan9 , please help test. Thanks!

**Comment by rakuco** [comment]
Does this also include @chuan9's recent commits ("[SIMD.js] Fix no exception thrown when get invalid index of Float32x4Array. Add test case for exception thrown when get invalid index of Float32x4Array" and "[SIMD.js] Fix offset of SIMD.Float32x4.load by adding tarray.byteOffset. Add test case for byteOffset of float32x4Array")?

**Comment by chuan9** [comment]
@rakuco yes, ningxin's m43 branch includes my patch, by the way, will you merge two commits about XWALK-3155 in current master? It seems a little confused.

**Comment by huningxin** [comment]
I squashed them into https://github.com/huningxin/v8-crosswalk/commit/4dfa98185324a23cb216405d0ffcb44901f5f6de.

**Comment by rakuco** [comment]
> will you merge two commits about XWALK-3155 in current master? It seems a little confused.

One of them (#96) is still being reviewed, so there's no way to merge them at the moment. I wasn't planning on squashing them together just because it's easier to just call `git rebase` and let it work with the existing commits. However, I'm not opposed to that if, for example, Ningxin squashes them when sending an updated version for 43.

**Comment by rakuco** [comment]
Ping. I'm about to start the process to move Crosswalk to M43, it would be nice if simd.js support was already in place.

**Comment by rakuco** [comment]
v8-crosswalk's next branch is now master. Can you please resend the PR and target the new branch?

**Comment by huningxin** [comment]
@rakuco , sure. I will send a new PR to master.

**Pull request closed without merging**
