### PR TITLE
[SIMD.js] Optimize SIMD operations by CrankShaft

### PR DESCRIPTION
**Pull request by chuan9**
M50: Enable simd.js in v8-crosswalk next.
BUG=XWALK-6685

### CODE REVIEW

**Comment by chuan9** [comment]
@rakuco Please have a check.

**Comment by rakuco** [comment]
My knowledge of the SIMD.js technicalities is zero, so I defer the review to @huningxin :-)
@mrunalk: fyi ^

From my side, please just make sure that `git cl format` is passing.

**Comment by chuan9** [comment]
@huningxin Will you help review it? Thanks!

**Comment by huningxin** [comment]
sure. I will look ASAP.

**Comment by huningxin** [comment]
@chuan9 , as this is a rebase PR, could you please list the new changes according to M50 adapting? It would help review much. Thanks!

**Comment by chuan9** [comment]
@huningxin According to conflicts, we did the following changes comparing to last version:
1. upstream remove (HAllocateBlockContext)[https://chromium.googlesource.com/v8/v8/+/e80279c02beddeec956536de54d563a4beb989a6%5E%21/] class and other related code. So we remove these this correspondingly.
2.Change variable's name from spill_slot_count_ to current_frame_slots_ in (lithium-ia32.cc)[https://github.com/crosswalk-project/v8-crosswalk/pull/146/files] and lithium-x64.cc
3.Upstream use (TranslatedState instead of deoptimizer)[https://bfff9e8-dot-chromiumcodereview-hr.appspot.com/1698743002/]. So remove FillInputFrame in deoptimizer-ia32.cc coompared with (m49 rebase)[https://github.com/crosswalk-project/v8-crosswalk/commit/18b37a71889737d6f29937586dac818bb6e85279].
4.revert SIMD128Register in assembler-mips.h and add our SIMD128Register, refer (m50 rebase patch)[https://github.com/crosswalk-project/v8-crosswalk/pull/146/files].
5.Both add upstream's change and our patch in [disasm-x64.cc]. Display code here since it's not easy to point out in the page.<pre><code>
1536 <<<<<<< HEAD
1537       } else if (third_byte == 0x0a) {
1538         get_modrm(*current, &mod, &regop, &rm);
1539         AppendToBuffer("roundss %s,", NameOfXMMRegister(regop));
1540         current += PrintRightXMMOperand(current);
1541         AppendToBuffer(",0x%x", (*current) & 3);
1542         current += 1;
1543 =======
1544       } else if (third_byte == 0x21) {
1545         get_modrm(*current, &mod, &regop, &rm);
1546         // insertps xmm, xmm, imm8
1547         AppendToBuffer("insertps %s,%s,%d", NameOfXMMRegister(regop),
1548                        NameOfXMMRegister(rm), (*(current + 1)) & 3);
1549         current += 2;
1550       } else if (third_byte == 0x22) {
1551         get_modrm(*current, &mod, &regop, &rm);
1552         // pinsrd xmm, reg32, imm8
1553         AppendToBuffer("pinsrd %s,%s,%d", NameOfXMMRegister(regop),
1554                        NameOfCPURegister(rm), (*(current + 1)) & 3);
1555         current += 2;
1556 >>>>>>> 18b37a7... [SIMD.js] Optimize SIMD operations by CrankShaft
</code></pre>

That's all, thank you~

**Comment by huningxin** [comment]
Thanks for the changelog. It helps so much!

LGTM.

**Comment by huningxin** [comment]
BTW, I believe put the changelog into the commit log would help others later.

**Comment by chuan9** [comment]
@huningxin Ok, I will add the log into commit and do the same things in the later rebase. Thanks!

**Comment by rakuco** [comment]
Please don't forget the coding style: I've run `git checkout -b next-test v8-crosswalk/next && git am -3 146.patch && git-cl format .` and there are plenty of changes in the diff.

**Comment by huningxin** [comment]
> I will add the log into commit and do the same things in the later rebase

Would you please do that for M50 rebase?

**Comment by huningxin** [comment]
Looks good. Thanks!

**Comment by chuan9** [comment]
@rakuco Done, the style is ok now. Thanks

**Comment by chuan9** [comment]
@rakuco  will you revert this patch? I will send a new PR with prevoius commits squashed.

**Comment by rakuco** [comment]
This has not been integrated yet, so there's nothing to revert.
In any case, you don't need to send a new pull request, it's better if you just update this one.

**Comment by chuan9** [comment]
@rakuco  ok, after you merge this patch, I will send new PR on it.

**Comment by mrunalk** [comment]
@chuan9 I am assuming after the style fixes you have merged your commits into one single commit. Also looking at Ningxin's approval I will merge this PR into next. Thanks for working on this.

**Pull request merged**
