### PR TITLE
Cherry pick of XDK heap profiler commits and several fixes due to chromium M42 migration

### PR DESCRIPTION
**Pull request by elvin-nnov**
There was several compilation errors after cherry-pick of XDK heap profiler 392f691 and 3901531 commits to chromium M42 version v8.
Bug fix consist of two parts
1. more strict warning handling. I believe they appear after clang usage
2. one of the construction in the v8 related to the marking of new block as FreeeSpace in the heap was slightly changed

### CODE REVIEW

**Comment by rakuco** [comment]
Can you please squash the M42 commit into the original ones? Otherwise the build will be broken between those commits, now and in all subsequent versions we release.

**Comment by elvin-nnov** [comment]
Do you mean squash a51dfda, 99e382b and 391e1a5 to one commit?

**Comment by rakuco** [comment]
I'm fine with a51dfda and 99e382b being separate, but 391e1a5 needs to be squashed into a51dfda.

**Comment by elvin-nnov** [comment]
I will squash all three together. Is it ok for you?
For me this will look solid because 99e382b and 391e1a5 just bug fixes of the main patch.

**Comment by rakuco** [comment]
Sure, that works as well.

**Comment by elvin-nnov** [comment]
squashed and added detailed description of the feature, its difference vs CDT Heap Profiler

**Comment by rakuco** [comment]
Merged, thank you!

**Pull request merged**
