### PR TITLE
SIMD.js Resolve error on arm64 in building

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-6190

### CODE REVIEW

**Comment by chuan9** [comment]
@rakuco it's oddball. All tests are passed but trybot failed. Is there some problems with tyrbot?

**Comment by rakuco** [comment]
It looks like the problem's with the slaves indeed. I'll take a look today.

**Comment by rakuco** [comment]
Sorry for the bug; the trybots did not adapt automatically to the move of the mozilla-tests repository from SVN to git, and I had to manually fix them. Things should work now, please resend the patch for it to be processed.

**Comment by rakuco** [comment]
ping @huningxin

**Comment by chuan9** [comment]
@rakuco Do you fix issues about trybot? The results are still failure. Help me have a look at this. Thanks!

**Comment by rakuco** [comment]
The failures are different now (the patch was not even being built before). I believe the bots may need additional RAM, which we'll address in the near future. I wouldn't worry about those test failures for now.

**Comment by rakuco** [comment]
Since the canary builds have been blocked on this since the end of last week and the patch doesn't seem to break the other architectures, I'll go ahead and merge this. If other things need to be worked on, they can be worked on later without the pressure of the broken canary builds.

**Pull request merged**
