### PR TITLE
[SIMD.js] Fix exception thrown when get Float32x4Array invalid index.

### PR DESCRIPTION
**Pull request by chuan9**
Add test case for exception thrown for Float32x4Array invalid index.

BUG=XWALK-2440

### CODE REVIEW

**Comment by chuan9** [comment]
@huningxin I change the branch to this and apply your changes

**Comment by huningxin** [comment]
Code LGTM. @chuan9 could you please update the commit title to "[SIMD.js] Fix no exception thrown when get invalid index of Float32x4Array"? It is more accurate. Thanks!

**Comment by chuan9** [comment]
yeah, you are right, I will rewrite commit. Thanks

**Comment by rakuco** [comment]
Alright, merging then. Thanks!

**Pull request merged**
