### PR TITLE
[SIMD.js] Fix the ARM64 and MIPS build after M45 rebasing

### PR DESCRIPTION
**Pull request by huningxin**
BUG=XWALK-5182

### CODE REVIEW

**Comment by huningxin** [comment]
Bots (ia32, x64 and ARM) are green. And ARM64 and MIPS passed compilation and testing on my dev machine.

@chuan9 @rakuco , please take a look. Thanks!

**Comment by rakuco** [comment]
thanks a lot for the quick fix!
feel free to merge if you don't need to wait for @chuan9's review. remember to roll `DEPS.xwalk` and then backport this fix to Crosswalk 15.

**Comment by chuan9** [comment]
@rakuco LGTM, thanks ningxin very much for fix!

**Comment by huningxin** [comment]
Thanks for review. I am going to merge it.

**Pull request merged**
