### PR TITLE
Add Bool32x4ExtractLane on x64

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-7000

### CODE REVIEW

**Comment by chuan9** [comment]
@huningxin Please help review, thanks

**Comment by rakuco** [comment]
I've just merged #154, can you resubmit for us to check the bots?

**Comment by chuan9** [comment]
of course, done

**Comment by huningxin** [comment]
LGTM. Thanks!

**Comment by chuan9** [comment]
@rakuco It seems that the trybot is still in abnormal state. Can you have a fix?

**Comment by rakuco** [comment]
I'm on holiday and unable to fix it this week. Since this is a fix for a release blocker and another iteration of the patch worked, go ahead and ignore the bots.

**Pull request merged**
