### PR TITLE
Rebase SIMD.js to M43

### PR DESCRIPTION
**Pull request by huningxin**

### CODE REVIEW

**Comment by rakuco** [comment]
ping @chuan9

**Comment by huningxin** [comment]
All green, thanks to @rakuco . Could you please merge it?

**Comment by rakuco** [comment]
it'd be good to get an lgtm from someone

**Comment by huningxin** [comment]
@chuan9 , please take a look. Thanks!

**Comment by chuan9** [comment]
@rakuco @huningxin  FYI, I have rebased the patch locally and tested it,  LGTM!

**Comment by huningxin** [comment]
Thanks for the review, @chuan9 !

**Comment by rakuco** [comment]
thanks everyone, please remember to roll `DEPS.xwalk` and uncomment out the code in Crosswalk that enables simd.js by default.

**Pull request merged**
