### PR TITLE
Cherry-pick SIMD.js turbofan patches to Crosswalk-14 M43 branch

### PR DESCRIPTION
**Pull request by huningxin**

### CODE REVIEW

**Comment by huningxin** [comment]
To address https://crosswalk-project.org/jira/browse/XWALK-3409 which targets Crosswalk 14. @rakuco , please take a look. Thanks!

**Comment by huningxin** [comment]
Please help roll v8 once merged. Thanks!

**Comment by rakuco** [comment]
I think this isn't necessary. Crosswalk 14 will use the current master,  it's just that we're in the process of updating it to a newer M43.

**Comment by huningxin** [comment]
Good to know that. Thanks. I am going to close it.

**Comment by huningxin** [comment]
@rakuco , however, the v8 sha1 in https://github.com/crosswalk-project/crosswalk/blob/master/DEPS.xwalk#L21 points to head of crosswalk-14/43.0.2357.18. Will you update that to master? I need to roll v8 after you finish that. Thanks.

**Comment by rakuco** [comment]
Yes, the update is ongoing (see crosswalk-project/crosswalk#3000). We've just nd out that ozone-wayland needs to be fixed though, so it still may take a day. If these two commits are really urgent, we could commit this PR and roll v8 in the meantime.

**Comment by huningxin** [comment]
@rakuco , you said Crosswalk 14 will use the current master, it would be fine, as these two patches are already in v8-crosswalk master. Could you please roll v8 sha1 to 18d5a56d258af85dbaba5b6835dd8bdb562e6b69 when you update DEPS.xwalk? Thanks!

**Pull request closed without merging**
