### PR TITLE
Revert "XDK Heap Profiler collector and XDK CPUProfiler"

### PR DESCRIPTION
**Pull request by rakuco**
This reverts commit 6e8bb75a4232f90de338374e6dd443f06a18feda.

This commit as-is breaks the M51 standalone build:

```
../test/cctest/test-cpu-profiler.cc:1626:29: error: no viable conversion from 'const std::vector<const v8::CpuProfileNode *>' to 'const v8::CpuProfileNode *'
  const v8::CpuProfileNode* start_node = GetChild(env, root, "start");
                            ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../test/cctest/test-cpu-profiler.cc:1628:29: error: no viable conversion from 'const std::vector<const v8::CpuProfileNode *>' to 'const v8::CpuProfileNode *'
  const v8::CpuProfileNode* level2_node = GetChild(env, level1_node, "level2");
                            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../test/cctest/test-profile-generator.cc:291:8: error: no matching member function for call to 'AddPathFromEnd'
  tree.AddPathFromEnd(path_vec);
  ~~~~~^~~~~~~~~~~~~~
.././src/profiler/profile-generator.h:215:16: note: candidate function not viable: no known conversion from 'Vector<i::StackEntry>' to 'const std::vector<StackEntry>' for 1st argument
  ProfileNode* AddPathFromEnd(
               ^
.././src/profiler/profile-generator.h:221:16: note: candidate function not viable: no known conversion from 'Vector<i::StackEntry>' to 'const std::vector<CodeEntry *>' for 1st argument
  ProfileNode* AddPathFromEnd(
               ^
../test/cctest/test-profile-generator.cc:324:8: error: no matching member function for call to 'AddPathFromEnd'
  tree.AddPathFromEnd(path_vec2);
  ~~~~~^~~~~~~~~~~~~~
.././src/profiler/profile-generator.h:215:16: note: candidate function not viable: no known conversion from 'Vector<i::StackEntry>' to 'const std::vector<StackEntry>' for 1st argument
  ProfileNode* AddPathFromEnd(
               ^
.././src/profiler/profile-generator.h:221:16: note: candidate function not viable: no known conversion from 'Vector<i::StackEntry>' to 'const std::vector<CodeEntry *>' for 1st argument
  ProfileNode* AddPathFromEnd(
               ^
```

### CODE REVIEW

**Comment by rakuco** [comment]
@mrunalk: the standalone V8 build has been broken for almost a week since you pushed the M51 V8, and it looks like you were not watching the bots once you pushed the rebased master.

To clarify: you should first push v8-crosswalk and chromium-crosswalk and only proceed with Crosswalk itself once you verify the forks are building correctly.

**Comment by r0b5t4** [comment]
rs+

**Comment by mrunalk** [comment]
@rakuco, It cannot be a week as I pushed M51 last Wednesday. :) I typically don't watch V8 bots as it's usually taken care of by SIMD folks, since there were no major changes to SIMD or XDK this time that somehow slipped through my mind. I will add that to my checklist from now on. Thanks for taking care of it.

**Comment by rakuco** [comment]
> @rakuco, It cannot be a week as I pushed M51 last Wednesday. :)

Er, sorry, I looked at the wrong dates.

**Pull request merged**
