### PR TITLE
Remove SIMD operation from deopt environment check

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-6662
Since we add deoptimization environment for SIMD in specific case, so it's possible to check failed if the code doesn't cause deoptimization. So remove environment check for SIMD operation to avoid check failed.

### CODE REVIEW

**Comment by chuan9** [comment]
@huningxin Please have a review. Thanks

**Comment by huningxin** [comment]
Any reason to disable the checks for SIMD ops?

**Comment by chuan9** [comment]
@huningxin Like XWALK-6662, it will check failed in debug version when there has no deoptimization, the root cause is we add deoptimization environment in some specific case and the environment is needed, so disable checks to avoid check failed.

**Comment by huningxin** [comment]
> the root cause is we add deoptimization environment in some specific case and the environment is needed, so disable checks to avoid check failed.

I am confused. If the deoptimization environment is needed, the lithium code should use it in code generation, e.g. [`DeoptimizeIf`](https://code.google.com/p/chromium/codesearch#chromium/src/v8/src/crankshaft/x64/lithium-codegen-x64.cc&q=RegisterEnvironmentForDeoptimization&sq=package:chromium&type=cs&l=706). In that case, the check should not fail.

Do you know which SIMD instructions hit this assertion? I don't think disable the check for all SIMD instruction is a right solution.

**Comment by chuan9** [comment]
@huningxin It will hit this assertion for all SIMD instructions which is added deoptimization environments. Because the code will only use deoptimizeIf if check failed in code generation and it will not cause check failed for environment in this situation. For SIMD.Float32x4, the deoptimization check code are as bellow:
<code>
    case kFloat32x4ExtractLane: {
      if (instr->hydrogen()->right()->IsConstant() &&
          HConstant::cast(instr->hydrogen()->right())->HasInteger32Value()) {
...
     } else {
       Comment(";;; deoptimize: non-constant selector for extractLane");
       DeoptimizeIf(no_condition, instr, Deoptimizer::kForcedDeoptToRuntime);
       return;
     }
</code>
  If the condition doesn't meet if judgement, it will go into else and cause DeoptimizaIf.
  Otherwise, it will never use DeoptimizeIf and will cause check environment fail.

**Comment by recbuilder** [comment]
Then the lithium code should assign environment when needed, let's say `(instr->hydrogen()->right()->IsConstant() && HConstant::cast(instr->hydrogen()->right())->HasInteger32Value())` in `kFloat32x4ExtractLane` case.

**Comment by huningxin** [comment]
Then the lithium code should assign environment when needed, let's say `(instr->hydrogen()->right()->IsConstant() && HConstant::cast(instr->hydrogen()->right())->HasInteger32Value())` in `kFloat32x4ExtractLane` case.

**Pull request closed without merging**
