### PR TITLE
[SIMD.js] Optimize SIMD128 operations by TurboFan

### PR DESCRIPTION
**Pull request by huningxin**
The implementation is only for ia32 and x64 ports.

Overall we have enabled 114 stable and core SIMD128 APIs (same as Crankshaft)
for three vector types (float32x4, int32x4 and float64x2) in TurboFan.
Performance speedup is expected(2x~9x) for several simd.js benchmarks.

Desgin background:
1. Introduce the types of float32x4, int32x4 and float64x2 to TurboFan's type
system.
2. Introduce opcode for both Node(TurboFan's HIR) and Instruction
(TurboFan's LIR) for each SIMD128 API.
3. For efficiency, all SIMD128 APIs are regarded as builtin functions and will be
inlined in the phase of JS typed lowering of TurboFan's pipeline.
4. For register allocation, we also need to introduce register types for
float32x4, int32x4 and float64x2 and guarantee to use xmm register and move to a
16-bytes stack slot if spilled.

TODOs
1. To support TurboFan OSR.
2. To support TurboFan deoptimization.

Conflicts:

	src/compiler/ast-graph-builder.h
	src/compiler/code-generator-impl.h
	src/compiler/frame.h
	src/compiler/graph-visualizer.cc
	src/compiler/ia32/code-generator-ia32.cc
	src/compiler/ia32/instruction-selector-ia32.cc
	src/compiler/instruction-codes.h
	src/compiler/instruction-selector.cc
	src/compiler/instruction.h
	src/compiler/js-builtin-reducer.cc
	src/compiler/js-builtin-reducer.h
	src/compiler/js-typed-lowering.cc
	src/compiler/machine-operator.cc
	src/compiler/machine-operator.h
	src/compiler/opcodes.h
	src/compiler/register-allocator.cc
	src/compiler/register-allocator.h
	src/compiler/simplified-lowering.cc
	src/compiler/simplified-operator.cc
	src/compiler/x64/code-generator-x64.cc
	src/compiler/x64/instruction-selector-x64.cc
	src/isolate.cc
	src/objects.cc

### CODE REVIEW

**Comment by huningxin** [comment]
@chuan9 , please take a look. Thanks!

**Comment by chuan9** [comment]
There is a little problem with build of arm debug version. FYI, log is as bellow:
make[1]: Entering directory `/home/lc/workspace/v8_crosswalk/v8-crosswalk-test-rebase/v8/out'
  LINK(host) /home/lc/workspace/v8_crosswalk/v8-crosswalk-test-rebase/v8/out/arm.debug/mksnapshot
../src/compiler/code-generator.cc:72: error: undefined reference to 'v8::internal::compiler::CodeGenerator::AssembleStopAt()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/home/lc/workspace/v8_crosswalk/v8-crosswalk-test-rebase/v8/out/arm.debug/mksnapshot] Error 1
make[1]: Leaving directory `/home/lc/workspace/v8_crosswalk/v8-crosswalk-test-rebase/v8/out'
make: *** [arm.debug] Error 2

**Comment by huningxin** [comment]
@chuan9 , thanks for the review. I pushed the fix. Please take another look!

**Comment by chuan9** [comment]
@huningxin Tested the patch and LGTM!

**Comment by huningxin** [comment]
Bots are green. I am going to merge it.

**Pull request merged**
