### PR TITLE
Change type name from all lower case to first Character upper case

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-4766

### CODE REVIEW

**Comment by rakuco** [comment]
Sorry, but looking at the PR message, the commit messages and the JIRA ticket it's still impossible to know why this is needed -- even the ticket just says "we need to do this", which isn't helpful in explaining _why_ we have to do this. The most plausible explanation I can find is that this is related to making it more spec-compliant because of the related JIRA ticket, but even if that's the case it should be made explicit.

Additionally, you should get rid of the "Conflicts" part of the commit messages.

**Comment by chuan9** [comment]
Yes, this implement is to make our patch compliant to new spec. I should add these message in PR.
Additionally, since this implement is made of two interdependent parts: runtime and crankshaft. Runtime parts should placed after runtime's implementation, and crankshaft parts should placed after crankshaft's implementation. So I think it's needed to rebase these PR to avoid "Conflicts".

**Comment by huningxin** [comment]
> Sorry, but looking at the PR message, the commit messages and the JIRA ticket it's still impossible to know why this is needed

@rakuco , thanks for the question. The JIRA ticket https://crosswalk-project.org/jira/browse/XWALK-4766 is part of blockers to https://crosswalk-project.org/jira/browse/XWALK-4765. The main purpose of XWALK-4765 is to make SIMD.js implementation in Crosswalk to be spec compliant. Otherwise, the benchmarks and optimizations (as gl-matrix mentioned in ticket) would not work on Crosswalk.

**Comment by huningxin** [comment]
@chuan9 , thanks for the PR. The code LGTM. Please update the commit message to remove the conflicts section as this is not a rebasing.

Once merged, in next rebase, we need to squash them into existing commits for Runtime and Crankshaft.

**Comment by chuan9** [comment]
@huningxin As you see, since build bot test the the newest commit, so the runtime's implementation in this PR will not cause any conflicts and the "Conflicts" in the first PR were already resolved in the second PR. So will you have a look at it and merge it?

**Comment by huningxin** [comment]
LGTM. Waiting for bots.

@rakuco , do you have any concerns?

**Comment by rakuco** [comment]
lgtm, please be more verbose in future commits, preferably one should not need to look elsewhere to figure out why a commit is necessary.

**Comment by rakuco** [comment]
remember to roll `DEPS.xwalk`.

**Pull request merged**
