### PR TITLE
[SIMD.js] Modify return type in deoptmization phase

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-4905
BUG=XWALK-6248

### CODE REVIEW

**Comment by rakuco** [comment]
@huningxin

**Comment by chuan9** [comment]
@huningxin Please have a review. and it's related to XWALK-6248

**Comment by huningxin** [comment]
Code LGTM. However trybot seems to fail.

**Comment by rakuco** [comment]
I fixed the Trybot failures yesterday; if you guys would like to be sure this change does not introduce any regressions, please resubmit the PR for it to be processed again.

**Comment by chuan9** [comment]
@rakuco It's ok now. Please merge it and I have other patches to submit.

**Comment by rakuco** [comment]
Do not forget you need to roll V8 in DEPS.xwalk

**Comment by chuan9** [comment]
@rakuco Thanks for tips! Welcome trybot back!

**Comment by rakuco** [comment]
@chuan9: we're going to branch Crosswalk 18 out of master soon, and the commit rolling `DEPS.xwalk` is likely not going to be part of where we branch from. Is this a bug fix? Would it need to go into the soon-to-be-created crosswalk-18 beta branch or can it just stay in master (Crosswalk 19)?

**Comment by chuan9** [comment]
@rakuco yes, it's a bug fix. This patch resolve two bugs BUG=XWALK-4905 and
BUG=XWALK-6248

**Comment by rakuco** [comment]
I see. I've just branched Crosswalk 18: https://lists.crosswalk-project.org/pipermail/crosswalk-dev/2016-February/003436.html
Can you send a PR cherry-picking this commit to the crosswalk-18/48.0.2564.97?

**Comment by rakuco** [comment]
I've created XWALK-6278 to track the cherry-pick.

**Pull request merged**
