### PR TITLE
M53 simd rebase

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-7249 
M53: Enable simd.js in v8-crosswalk next.
Conflicts log:
    1. Add simd128_registers in [RegisterConfiguration](https://cs.chromium.org/chromium/src/v8/src/register-configuration.h?q=simd128_registers&sq=package:chromium&l=141&dr=CSs) to get register name.It's   a temp solution to avoid build failure. Will use other upstream implementations in the next rebase.
    2. Remove some instructions to align with upstream's change on x64 arch.
    3. Change xmm scratch from xmm0 to [xmm15](https://cs.chromium.org/chromium/src/v8/src/crankshaft/x64/lithium-codegen-x64.h?sq=package:chromium&dr&rcl=1471966011&l=118) on x64 arch.

### CODE REVIEW

**Comment by chuan9** [comment]
@huningxin Please have a review. Thanks!

**Comment by chuan9** [comment]
@huningxin Will you help check this PR? Thanks!

**Comment by mrunalk** [comment]
@chuan9 FYI, I have updated the v8 repo so you will have to rebase your changes with latest.

**Comment by chuan9** [comment]
@mrunalk Thanks for hints, I refreshed the PR. @huningxin Please have a review. Thanks

**Comment by huningxin** [comment]
LGTM. Thanks!

**Pull request merged**
