### PR TITLE
[simd128.js]  Fix offset of SIMD.Float32x4.load by adding tarray.byteOff

### PR DESCRIPTION
**Pull request by chuan9**
BUG=XWALK-3155

### CODE REVIEW

**Comment by huningxin** [comment]
@chuan9 , thanks for the fix. Could you please add test cases for this issue? So we can track it better later.

**Comment by chuan9** [comment]
Of course, May I ask where should I add test cases?

**Comment by huningxin** [comment]
Please add them into test/mjsunit/simd

**Comment by chuan9** [comment]
got it

**Pull request closed without merging**
